name: bende_fazla_final
description: My Graduate App
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: '>=3.1.0-262.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  lottie: ^2.6.0
  photo_manager: ^2.8.1
  image_picker: ^1.0.5
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  
  # Cache
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
      - family: OleoScript
        fonts:
          - asset: assets/fonts/Oleo-Script/OleoScript-Bold.ttf
          - asset: assets/fonts/Oleo-Script/OleoScript-Regular.ttf

      - family: SF Pro Text
        fonts:
          - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Regular.otf
            weight: 400
          - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-RegularItalic.otf
            weight: 400
            style: italic
          - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Medium.otf
            weight: 500
          - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-MediumItalic.otf
            weight: 500
            style: italic
          - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Semibold.otf
            weight: 600
          - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-SemiboldItalic.otf
            weight: 600
            style: italic
          - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Bold.otf
            weight: 700
          - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-BoldItalic.otf
            weight: 700
            style: italic