// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC31_FZhdzY7k6p7HUNaDtPC_ZOdiCKjEM',
    appId: '1:400272318117:web:088c9695369e657996774c',
    messagingSenderId: '400272318117',
    projectId: 'fir-auth-a69ce',
    authDomain: 'fir-auth-a69ce.firebaseapp.com',
    storageBucket: 'fir-auth-a69ce.appspot.com',
    measurementId: 'G-P8GCDYTTK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3ROkkFV6gfaiXg7FjUqaMN8IgVaxK3s',
    appId: '1:400272318117:android:856cf9cf5864cd4096774c',
    messagingSenderId: '400272318117',
    projectId: 'fir-auth-a69ce',
    storageBucket: 'fir-auth-a69ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6cFy_SLRG68OAWmaKNdTz1XdM4jNei_U',
    appId: '1:400272318117:ios:fd56d3743ab0f33396774c',
    messagingSenderId: '400272318117',
    projectId: 'fir-auth-a69ce',
    storageBucket: 'fir-auth-a69ce.appspot.com',
    iosBundleId: 'com.example.bendeFazlaFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6cFy_SLRG68OAWmaKNdTz1XdM4jNei_U',
    appId: '1:400272318117:ios:83627a226c468b1396774c',
    messagingSenderId: '400272318117',
    projectId: 'fir-auth-a69ce',
    storageBucket: 'fir-auth-a69ce.appspot.com',
    iosBundleId: 'com.example.bendeFazlaFinal.RunnerTests',
  );
}
